from fastapi import FastAPI, HTTPException
from typing import List, Dict
from stamp_uuid import generate_stamp_uuid

tags_metadata = [
    {
        "name": "Get all ids",
        "description": "creates and gets all the unique ids that has ever been generated by the system",
    }
]


app = FastAPI(
    title="A unique id generator",
    description="A simple API built with FastAPI that generates uuid's together with the timestamp when it was created",
    version="1.0.0",
    openapi_tags=tags_metadata,
)


@app.get("/get-ids", status_code=201, tags=["Get all ids"])
# returns a list of dictionaries
async def generate_and_get_ids() -> List[Dict[str, str]]:
    try:
        return generate_stamp_uuid()

    except HTTPException as h:
        print(h)
        return {"error": h}
